const chatsuboCyberdeck = {
  AI: "71226",
  "Fuji Electric": "6124",
  "Zion Cluster": "43267",
  "Chiba City": "3347",
  "Asano Computing": "061254",
  "Hitachi Biotech": "672",
  Cryptology: "67237",
  "Space Colony": "054127",
  "Holy Joystick": "333",
  "Bank of Berne": "5165",
  Spacedock: "031770",
  "Ono-Sendai": "725",
  "Marcus Garvey": "45771",
  "Bank of Zurich": "1053",
  "Compu-judge": "054",
  flatline: "132077",
};

const chatsuboComlink = {
  AI: "42074",
  "Fuji Electric": "2174",
  "Zion Cluster": "34770",
  "Chiba City": "3601",
  "Asano Computing": "073611",
  "Hitachi Biotech": "614",
  Cryptology: "74655",
  "Space Colony": "056201",
  "Holy Joystick": "673",
  "Bank of Berne": "6160",
  Spacedock: "031776",
  "Ono-Sendai": "507",
  "Marcus Garvey": "31270",
  "Bank of Zurich": "0017",
  "Compu-judge": "410",
  flatline: "014527",
};

const chatsuboIcebreaker = {
  AI: "22372",
  "Fuji Electric": "6162",
  "Zion Cluster": "70012",
  "Chiba City": "1316",
  "Asano Computing": "162324",
  "Hitachi Biotech": "473",
  Cryptology: "50127",
  "Space Colony": "157233",
  "Holy Joystick": "533",
  "Bank of Berne": "5116",
  Spacedock: "067144",
  "Ono-Sendai": "072",
  "Marcus Garvey": "51666",
  "Bank of Zurich": "5165",
  "Compu-judge": "300",
  flatline: "030654",
};

const chatsuboROMConstruct = {
  AI: "00206",
  "Fuji Electric": "5150",
  "Zion Cluster": "61543",
  "Chiba City": "4120",
  "Asano Computing": "063124",
  "Hitachi Biotech": "424",
  Cryptology: "36112",
  "Space Colony": "051435",
  "Holy Joystick": "017",
  "Bank of Berne": "0170",
  Spacedock: "127170",
  "Ono-Sendai": "321",
  "Marcus Garvey": "61723",
  "Bank of Zurich": "6160",
  "Compu-judge": "434",
  flatline: "126443",
};

const chatsuboCowboy = {
  AI: "71724",
  "Fuji Electric": "6040",
  "Zion Cluster": "76631",
  "Chiba City": "0072",
  "Asano Computing": "131265",
  "Hitachi Biotech": "024",
  Cryptology: "61645",
  "Space Colony": "004713",
  "Holy Joystick": "254",
  "Bank of Berne": "4102",
  Spacedock: "061254",
  "Ono-Sendai": "672",
  "Marcus Garvey": "65110",
  "Bank of Zurich": "5116",
  "Compu-judge": "333",
  flatline: "114352",
};

const chatsuboEmperorNorton = {
  AI: "23671",
  "Fuji Electric": "0703",
  "Zion Cluster": "4321",
  "Chiba City": "4300",
  "Asano Computing": "060734",
  "Hitachi Biotech": "714",
  Cryptology: "07362",
  "Space Colony": "040327",
  "Holy Joystick": "700",
  "Bank of Berne": "7107",
  Spacedock: "073611",
  "Ono-Sendai": "614",
  "Marcus Garvey": "21400",
  "Bank of Zurich": "0170",
  "Compu-judge": "673",
  flatline: "054127",
};

const chatsuboCyberjack = {
  AI: "34755",
  "Fuji Electric": "4327",
  "Zion Cluster": "71312",
  "Chiba City": "1337",
  "Asano Computing": "113667",
  "Hitachi Biotech": "236",
  Cryptology: "61255",
  "Space Colony": "152777",
  "Holy Joystick": "512",
  "Bank of Berne": "5517",
  Spacedock: "162324",
  "Ono-Sendai": "473",
  "Marcus Garvey": "43267",
  "Bank of Zurich": "4102",
  "Compu-judge": "533",
  flatline: "056201",
};

const chatsuboRatz = {
  AI: "67237",
  "Fuji Electric": "2730",
  "Zion Cluster": "44312",
  "Chiba City": "6124",
  "Asano Computing": "021655",
  "Hitachi Biotech": "045",
  Cryptology: "01326",
  "Space Colony": "152336",
  "Holy Joystick": "213",
  "Bank of Berne": "0177",
  Spacedock: "063124",
  "Ono-Sendai": "424",
  "Marcus Garvey": "34770",
  "Bank of Zurich": "7107",
  "Compu-judge": "017",
  flatline: "157223",
};

const chatsuboHolografix = {
  AI: "74655",
  "Fuji Electric": "1777",
  "Zion Cluster": "61456",
  "Chiba City": "2174",
  "Asano Computing": "115721",
  "Hitachi Biotech": "103",
  Cryptology: "61627",
  "Space Colony": "013026",
  "Holy Joystick": "167",
  "Bank of Berne": "3121",
  Spacedock: "131265",
  "Ono-Sendai": "024",
  "Marcus Garvey": "70012",
  "Bank of Zurich": "5517",
  "Compu-judge": "254",
  flatline: "051435",
};

const chatsuboLarryMoe = {
  AI: "50127",
  "Fuji Electric": "3347",
  "Zion Cluster": "41317",
  "Chiba City": "6162",
  "Asano Computing": "011772",
  "Hitachi Biotech": "775",
  Cryptology: "71226",
  "Space Colony": "036160",
  "Holy Joystick": "616",
  "Bank of Berne": "6116",
  Spacedock: "060734",
  "Ono-Sendai": "714",
  "Marcus Garvey": "61543",
  "Bank of Zurich": "0177",
  "Compu-judge": "700",
  flatline: "004713",
};

const chatsuboPAX = {
  AI: "36112",
  "Fuji Electric": "3601",
  "Zion Cluster": "45771",
  "Chiba City": "5150",
  "Asano Computing": "117372",
  "Hitachi Biotech": "430",
  Cryptology: "42074",
  "Space Colony": "067123",
  "Holy Joystick": "733",
  "Bank of Berne": "5120",
  Spacedock: "113667",
  "Ono-Sendai": "236",
  "Marcus Garvey": "76631",
  "Bank of Zurich": "3121",
  "Compu-judge": "512",
  flatline: "040327",
};

const chatsuboSkillChips = {
  AI: "61645",
  "Fuji Electric": "1316",
  "Zion Cluster": "31270",
  "Chiba City": "6040",
  "Asano Computing": "121777",
  "Hitachi Biotech": "571",
  Cryptology: "22372",
  "Space Colony": "130277",
  "Holy Joystick": "313",
  "Bank of Berne": "0423",
  Spacedock: "021655",
  "Ono-Sendai": "045",
  "Marcus Garvey": "44321",
  "Bank of Zurich": "6116",
  "Compu-judge": "213",
  flatline: "152777",
};

const chatsuboShinsPawn = {
  AI: "07362",
  "Fuji Electric": "4120",
  "Zion Cluster": "51666",
  "Chiba City": "0703",
  "Asano Computing": "031770",
  "Hitachi Biotech": "725",
  Cryptology: "00206",
  "Space Colony": "014527",
  "Holy Joystick": "054",
  "Bank of Berne": "3173",
  Spacedock: "115721",
  "Ono-Sendai": "103",
  "Marcus Garvey": "71312",
  "Bank of Zurich": "5120",
  "Compu-judge": "167",
  flatline: "152336",
};

const chatsuboGentlemanLoser = {
  AI: "61255",
  "Fuji Electric": "0072",
  "Zion Cluster": "61723",
  "Chiba City": "4327",
  "Asano Computing": "031776",
  "Hitachi Biotech": "507",
  Cryptology: "71724",
  "Space Colony": "030654",
  "Holy Joystick": "410",
  "Bank of Berne": "5423",
  Spacedock: "011772",
  "Ono-Sendai": "775",
  "Marcus Garvey": "44312",
  "Bank of Zurich": "0423",
  "Compu-judge": "616",
  flatline: "013026",
};

const chatsuboMaasBiolabs = {
  AI: "01326",
  "Fuji Electric": "4300",
  "Zion Cluster": "65110",
  "Chiba City": "2730",
  "Asano Computing": "067144",
  "Hitachi Biotech": "072",
  Cryptology: "23671",
  "Space Colony": "126443",
  "Holy Joystick": "300",
  "Bank of Berne": "1053",
  Spacedock: "117372",
  "Ono-Sendai": "430",
  "Marcus Garvey": "61456",
  "Bank of Zurich": "3173",
  "Compu-judge": "733",
  flatline: "036160",
};

const chatsuboJusticeBooth = {
  AI: "61627",
  "Fuji Electric": "1337",
  "Zion Cluster": "21400",
  "Chiba City": "1777",
  "Asano Computing": "127170",
  "Hitachi Biotech": "321",
  Cryptology: "34755",
  "Space Colony": "114352",
  "Holy Joystick": "434",
  "Bank of Berne": "0017",
  Spacedock: "121777",
  "Ono-Sendai": "571",
  "Marcus Garvey": "41317",
  "Bank of Zurich": "5423",
  "Compu-judge": "313",
  flatline: "067123",
};

const theMatrix = {
  Chatsubo: {
    Cyberdeck: chatsuboCyberdeck,
    Comlink: chatsuboComlink,
    Icebreaker: chatsuboIcebreaker,
    "Rom Construct": chatsuboROMConstruct,
    Cowboy: chatsuboCowboy,
    "Emperor Norton": chatsuboEmperorNorton,
    Cyberjack: chatsuboCyberjack,
    Ratz: chatsuboRatz,
    Holografix: chatsuboHolografix,
    "Larry Moe": chatsuboLarryMoe,
    PAX: chatsuboPAX,
    "Skill chips": chatsuboSkillChips,
    "Shin's Pawn": chatsuboShinsPawn,
    "Gentleman Loser": chatsuboGentlemanLoser,
    "Maas Biolabs": chatsuboMaasBiolabs,
    "Justice Booth": chatsuboJusticeBooth,
  },
  Cyberspace: {
    Comlink: chatsuboCyberdeck,
    Icebreaker: chatsuboComlink,
    "Rom Construct": chatsuboIcebreaker,
    Cowboy: chatsuboROMConstruct,
    "Emperor Norton": chatsuboCowboy,
    Cyberjack: chatsuboEmperorNorton,
    Ratz: chatsuboCyberjack,
    Holografix: chatsuboRatz,
    "Larry Moe": chatsuboHolografix,
    PAX: chatsuboLarryMoe,
    "Skill chips": chatsuboPAX,
    "Shin's Pawn": chatsuboSkillChips,
    "Gentleman Loser": chatsuboShinsPawn,
    "Maas Biolabs": chatsuboGentlemanLoser,
    "Justice Booth": chatsuboMaasBiolabs,
    Cyberdeck: chatsuboJusticeBooth,
  },
  Gemeinschaft: {
    Icebreaker: chatsuboCyberdeck,
    "Rom Construct": chatsuboComlink,
    Cowboy: chatsuboIcebreaker,
    "Emperor Norton": chatsuboROMConstruct,
    Cyberjack: chatsuboCowboy,
    Ratz: chatsuboEmperorNorton,
    Holografix: chatsuboCyberjack,
    "Larry Moe": chatsuboRatz,
    PAX: chatsuboHolografix,
    "Skill chips": chatsuboLarryMoe,
    "Shin's Pawn": chatsuboPAX,
    "Gentleman Loser": chatsuboSkillChips,
    "Maas Biolabs": chatsuboShinsPawn,
    "Justice Booth": chatsuboGentlemanLoser,
    Cyberdeck: chatsuboMaasBiolabs,
    Comlink: chatsuboJusticeBooth,
  },
  "Crazy Edo": {
    "Rom Construct": chatsuboCyberdeck,
    Cowboy: chatsuboComlink,
    "Emperor Norton": chatsuboIcebreaker,
    Cyberjack: chatsuboROMConstruct,
    Ratz: chatsuboCowboy,
    Holografix: chatsuboEmperorNorton,
    "Larry Moe": chatsuboCyberjack,
    PAX: chatsuboRatz,
    "Skill chips": chatsuboHolografix,
    "Shin's Pawn": chatsuboLarryMoe,
    "Gentleman Loser": chatsuboPAX,
    "Maas Biolabs": chatsuboSkillChips,
    "Justice Booth": chatsuboShinsPawn,
    Cyberdeck: chatsuboGentlemanLoser,
    Comlink: chatsuboMaasBiolabs,
    Icebreaker: chatsuboJusticeBooth,
  },
  Microsofts: {
    Cowboy: chatsuboCyberdeck,
    "Emperor Norton": chatsuboComlink,
    Cyberjack: chatsuboIcebreaker,
    Ratz: chatsuboROMConstruct,
    Holografix: chatsuboCowboy,
    "Larry Moe": chatsuboEmperorNorton,
    PAX: chatsuboCyberjack,
    "Skill chips": chatsuboRatz,
    "Shin's Pawn": chatsuboHolografix,
    "Gentleman Loser": chatsuboLarryMoe,
    "Maas Biolabs": chatsuboPAX,
    "Justice Booth": chatsuboSkillChips,
    Cyberdeck: chatsuboShinsPawn,
    Comlink: chatsuboGentlemanLoser,
    Icebreaker: chatsuboMaasBiolabs,
    "Rom Construct": chatsuboJusticeBooth,
  },
  "Cheap Hotel": {
    "Emperor Norton": chatsuboCyberdeck,
    Cyberjack: chatsuboComlink,
    Ratz: chatsuboIcebreaker,
    Holografix: chatsuboROMConstruct,
    "Larry Moe": chatsuboCowboy,
    PAX: chatsuboEmperorNorton,
    "Skill chips": chatsuboCyberjack,
    "Shin's Pawn": chatsuboRatz,
    "Gentleman Loser": chatsuboHolografix,
    "Maas Biolabs": chatsuboLarryMoe,
    "Justice Booth": chatsuboPAX,
    Cyberdeck: chatsuboSkillChips,
    Comlink: chatsuboShinsPawn,
    Icebreaker: chatsuboGentlemanLoser,
    "Rom Construct": chatsuboMaasBiolabs,
    Cowboy: chatsuboJusticeBooth,
  },
  "Julius Deane": {
    Cyberjack: chatsuboCyberdeck,
    Ratz: chatsuboComlink,
    Holografix: chatsuboIcebreaker,
    "Larry Moe": chatsuboROMConstruct,
    PAX: chatsuboCowboy,
    "Skill chips": chatsuboEmperorNorton,
    "Shin's Pawn": chatsuboCyberjack,
    "Gentleman Loser": chatsuboRatz,
    "Maas Biolabs": chatsuboHolografix,
    "Justice Booth": chatsuboLarryMoe,
    Cyberdeck: chatsuboPAX,
    Comlink: chatsuboSkillChips,
    Icebreaker: chatsuboShinsPawn,
    "Rom Construct": chatsuboGentlemanLoser,
    Cowboy: chatsuboMaasBiolabs,
    "Emperor Norton": chatsuboJusticeBooth,
  },
  "Donut World": {
    Ratz: chatsuboCyberdeck,
    Holografix: chatsuboComlink,
    "Larry Moe": chatsuboIcebreaker,
    PAX: chatsuboROMConstruct,
    "Skill chips": chatsuboCowboy,
    "Shin's Pawn": chatsuboEmperorNorton,
    "Gentleman Loser": chatsuboCyberjack,
    "Maas Biolabs": chatsuboRatz,
    "Justice Booth": chatsuboHolografix,
    Cyberdeck: chatsuboLarryMoe,
    Comlink: chatsuboPAX,
    Icebreaker: chatsuboSkillChips,
    "Rom Construct": chatsuboShinsPawn,
    Cowboy: chatsuboGentlemanLoser,
    "Emperor Norton": chatsuboMaasBiolabs,
    Cyberjack: chatsuboJusticeBooth,
  },
  Lawbot: {
    Holografix: chatsuboCyberdeck,
    "Larry Moe": chatsuboComlink,
    PAX: chatsuboIcebreaker,
    "Skill chips": chatsuboROMConstruct,
    "Shin's Pawn": chatsuboCowboy,
    "Gentleman Loser": chatsuboEmperorNorton,
    "Maas Biolabs": chatsuboCyberjack,
    "Justice Booth": chatsuboRatz,
    Cyberdeck: chatsuboHolografix,
    Comlink: chatsuboLarryMoe,
    Icebreaker: chatsuboPAX,
    "Rom Construct": chatsuboSkillChips,
    Cowboy: chatsuboShinsPawn,
    "Emperor Norton": chatsuboGentlemanLoser,
    Cyberjack: chatsuboMaasBiolabs,
    Ratz: chatsuboJusticeBooth,
  },
  database: {
    "Larry Moe": chatsuboCyberdeck,
    PAX: chatsuboComlink,
    "Skill chips": chatsuboIcebreaker,
    "Shin's Pawn": chatsuboROMConstruct,
    "Gentleman Loser": chatsuboCowboy,
    "Maas Biolabs": chatsuboEmperorNorton,
    "Justice Booth": chatsuboCyberjack,
    Cyberdeck: chatsuboRatz,
    Comlink: chatsuboHolografix,
    Icebreaker: chatsuboLarryMoe,
    "Rom Construct": chatsuboPAX,
    Cowboy: chatsuboSkillChips,
    "Emperor Norton": chatsuboShinsPawn,
    Cyberjack: chatsuboGentlemanLoser,
    Ratz: chatsuboMaasBiolabs,
    Holografix: chatsuboJusticeBooth,
  },
  Shiva: {
    PAX: chatsuboCyberdeck,
    "Skill chips": chatsuboComlink,
    "Shin's Pawn": chatsuboIcebreaker,
    "Gentleman Loser": chatsuboROMConstruct,
    "Maas Biolabs": chatsuboCowboy,
    "Justice Booth": chatsuboEmperorNorton,
    Cyberdeck: chatsuboCyberjack,
    Comlink: chatsuboRatz,
    Icebreaker: chatsuboHolografix,
    "Rom Construct": chatsuboLarryMoe,
    Cowboy: chatsuboPAX,
    "Emperor Norton": chatsuboSkillChips,
    Cyberjack: chatsuboShinsPawn,
    Ratz: chatsuboGentlemanLoser,
    Holografix: chatsuboMaasBiolabs,
    "Larry Moe": chatsuboJusticeBooth,
  },
  Freeside: {
    "Skill chips": chatsuboCyberdeck,
    "Shin's Pawn": chatsuboComlink,
    "Gentleman Loser": chatsuboIcebreaker,
    "Maas Biolabs": chatsuboROMConstruct,
    "Justice Booth": chatsuboCowboy,
    Cyberdeck: chatsuboEmperorNorton,
    Comlink: chatsuboCyberjack,
    Icebreaker: chatsuboRatz,
    "Rom Construct": chatsuboHolografix,
    Cowboy: chatsuboLarryMoe,
    "Emperor Norton": chatsuboPAX,
    Cyberjack: chatsuboSkillChips,
    Ratz: chatsuboShinsPawn,
    Holografix: chatsuboGentlemanLoser,
    "Larry Moe": chatsuboMaasBiolabs,
    PAX: chatsuboJusticeBooth,
  },
  softwarez: {
    "Shin's Pawn": chatsuboCyberdeck,
    "Gentleman Loser": chatsuboComlink,
    "Maas Biolabs": chatsuboIcebreaker,
    "Justice Booth": chatsuboROMConstruct,
    Cyberdeck: chatsuboCowboy,
    Comlink: chatsuboEmperorNorton,
    Icebreaker: chatsuboCyberjack,
    "Rom Construct": chatsuboRatz,
    Cowboy: chatsuboHolografix,
    "Emperor Norton": chatsuboLarryMoe,
    Cyberjack: chatsuboPAX,
    Ratz: chatsuboSkillChips,
    Holografix: chatsuboShinsPawn,
    "Larry Moe": chatsuboGentlemanLoser,
    PAX: chatsuboMaasBiolabs,
    "Skill chips": chatsuboJusticeBooth,
  },
  Matrix: {
    "Gentleman Loser": chatsuboCyberdeck,
    "Maas Biolabs": chatsuboComlink,
    "Justice Booth": chatsuboIcebreaker,
    Cyberdeck: chatsuboROMConstruct,
    Comlink: chatsuboCowboy,
    Icebreaker: chatsuboEmperorNorton,
    "Rom Construct": chatsuboCyberjack,
    Cowboy: chatsuboRatz,
    "Emperor Norton": chatsuboHolografix,
    Cyberjack: chatsuboLarryMoe,
    Ratz: chatsuboPAX,
    Holografix: chatsuboSkillChips,
    "Larry Moe": chatsuboShinsPawn,
    PAX: chatsuboGentlemanLoser,
    "Skill chips": chatsuboMaasBiolabs,
    "Shin's Pawn": chatsuboJusticeBooth,
  },
  "Matt Shaw": {
    "Maas Biolabs": chatsuboCyberdeck,
    "Justice Booth": chatsuboComlink,
    Cyberdeck: chatsuboIcebreaker,
    Comlink: chatsuboROMConstruct,
    Icebreaker: chatsuboCowboy,
    "Rom Construct": chatsuboEmperorNorton,
    Cowboy: chatsuboCyberjack,
    "Emperor Norton": chatsuboRatz,
    Cyberjack: chatsuboHolografix,
    Ratz: chatsuboLarryMoe,
    Holografix: chatsuboPAX,
    "Larry Moe": chatsuboSkillChips,
    PAX: chatsuboShinsPawn,
    "Skill chips": chatsuboGentlemanLoser,
    "Shin's Pawn": chatsuboMaasBiolabs,
    "Gentleman Loser": chatsuboJusticeBooth,
  },
  "Night City News": {
    "Justice Booth": chatsuboCyberdeck,
    Cyberdeck: chatsuboComlink,
    Comlink: chatsuboIcebreaker,
    Icebreaker: chatsuboROMConstruct,
    "Rom Construct": chatsuboCowboy,
    Cowboy: chatsuboEmperorNorton,
    "Emperor Norton": chatsuboCyberjack,
    Cyberjack: chatsuboRatz,
    Ratz: chatsuboHolografix,
    Holografix: chatsuboLarryMoe,
    "Larry Moe": chatsuboPAX,
    PAX: chatsuboSkillChips,
    "Skill chips": chatsuboShinsPawn,
    "Shin's Pawn": chatsuboGentlemanLoser,
    "Gentleman Loser": chatsuboMaasBiolabs,
    "Maas Biolabs": chatsuboJusticeBooth,
  },
};
