// import useEffect from "react";

// useEffect(() => {
//   console.log("before", Object.keys(wheelData.Cyberspace));
//   axios
//     .get("http://localhost:5555/datawheel/fetchdata?term=cyberspace")
//     .then((res) => {
//       // console.log(res.data);
//       wheelData.Chatsubo = res.data;
//     })
//     .then(console.log("after", Object.keys(wheelData.Cyberspace)));
// }, []);

// console.log(JSON.stringify(cyberspace));

const chatsubo = {
  Cyberdeck: { AI: 71226, "Fuji Electric": 6124 },
  Comlink: "",
  Icebreaker: "",
  "ROM construct": "",
  Cowboy: "",
  "Emperor Norton": "",
  Cyberjack: "",
  Ratz: { "Zion Cluster": 44312, "Chiba City": 6124 },
  Holografix: { "Asano Computing": 115721, "Hitachi Biotech": 103 },
  "Larry Moe": { Cryptology: 71226 },
  PAX: { "Space colony": "067123", "Holy Joystick": 733 },
  "Skill chips": { "Bank of Berne": "0423" },
  "Shin's Pawn": { Spacedock: 115721, "Ono-Sendai": 103 },
  "Gentleman Loser": { "Marcus Garvey": 44312, "Bank of Zurich": "0423" },
  "Maas Biolabs": { "Compu-judge": 733 },
  "Justice Booth": { flatline: "067123" },
};

const cyberspace = {
  Cyberdeck: { AI: 61627, "Fuji Electric": 1337 },
  Comlink: "",
  Icebreaker: "",
  "ROM construct": "",
  Cowboy: "",
  "Emperor Norton": "",
  Cyberjack: "",
  Ratz: { "Zion Cluster": 71312, "Chiba City": 1337 },
  Holografix: { "Asano Computing": "021655", "Hitachi Biotech": "045" },
  "Larry Moe": { Cryptology: 61627 },
  PAX: { "Space colony": "036160", "Holy Joystick": 616 },
  "Skill chips": { "Bank of Berne": 5120 },
  "Shin's Pawn": { Spacedock: "021655", "Ono-Sendai": "045" },
  "Gentleman Loser": { "Marcus Garvey": 71312, "Bank of Zurich": 5120 },
  "Maas Biolabs": { "Compu-judge": 616 },
  "Justice Booth": { flatline: "036160" },
};

const gemeinschaft = {
  Cyberdeck: { AI: "01326", "Fuji Electric": 4300 },
  Comlink: "",
  Icebreaker: "",
  "ROM construct": "",
  Cowboy: "",
  "Emperor Norton": "",
  Cyberjack: "",
  Ratz: { "Zion Cluster": 44312, "Chiba City": 4300 },
  Holografix: { "Asano Computing": 113667, "Hitachi Biotech": 236 },
  "Larry Moe": { Cryptology: "01326" },
  PAX: { "Space colony": "013026", "Holy Joystick": 167 },
  "Skill chips": { "Bank of Berne": 6116 },
  "Shin's Pawn": { Spacedock: 113667, "Ono-Sendai": 236 },
  "Gentleman Loser": { "Marcus Garvey": 44321, "Bank of Zurich": 6116 },
  "Maas Biolabs": { "Compu-judge": 167 },
  "Justice Booth": { flatline: "013026" },
};

const crazyEdo = {
  Cyberdeck: { AI: 61255, "Fuji Electric": "0072" },
  Comlink: "",
  Icebreaker: "",
  "ROM construct": "",
  Cowboy: "",
  "Emperor Norton": "",
  Cyberjack: "",
  Ratz: { "Zion Cluster": 76631, "Chiba City": "0072" },
  Holografix: { "Asano Computing": "060734", "Hitachi Biotech": 714 },
  "Larry Moe": { Cryptology: 61255 },
  PAX: { "Space colony": 152336, "Holy Joystick": 213 },
  "Skill chips": { "Bank of Berne": 3121 },
  "Shin's Pawn": { Spacedock: "060734", "Ono-Sendai": 714 },
  "Gentleman Loser": { "Marcus Garvey": 76631, "Bank of Zurich": 3121 },
  "Maas Biolabs": { "Compu-judge": 213 },
  "Justice Booth": { flatline: 152336 },
};

const microsofts = {
  Cyberdeck: { AI: "07362", "Fuji Electric": 4120 },
  Comlink: "",
  Icebreaker: "",
  "ROM construct": "",
  Cowboy: "",
  "Emperor Norton": "",
  Cyberjack: "",
  Ratz: { "Zion Cluster": 61543, "Chiba City": 4120 },
  Holografix: { "Asano Computing": 131265, "Hitachi Biotech": "024" },
  "Larry Moe": { Cryptology: "07362" },
  PAX: { "Space colony": 152777, "Holy Joystick": 512 },
  "Skill chips": { "Bank of Berne": "0177" },
  "Shin's Pawn": { Spacedock: 131265, "Ono-Sendai": "024" },
  "Gentleman Loser": { "Marcus Garvey": 61543, "Bank of Zurich": "0177" },
  "Maas Biolabs": { "Compu-judge": 512 },
  "Justice Booth": { flatline: 152777 },
};

const cheapHotel = {
  Cyberdeck: { AI: 61645, "Fuji Electric": 1316 },
  Comlink: "",
  Icebreaker: "",
  "ROM construct": "",
  Cowboy: "",
  "Emperor Norton": "",
  Cyberjack: "",
  Ratz: { "Zion Cluster": 70012, "Chiba City": 1316 },
  Holografix: { "Asano Computing": "063124", "Hitachi Biotech": 424 },
  "Larry Moe": { Cryptology: 61645 },
  PAX: { "Space colony": "040327", "Holy Joystick": 700 },
  "Skill chips": { "Bank of Berne": 5517 },
  "Shin's Pawn": { Spacedock: "063124", "Ono-Sendai": 424 },
  "Gentleman Loser": { "Marcus Garvey": 70012, "Bank of Zurich": 5517 },
  "Maas Biolabs": { "Compu-judge": 700 },
  "Justice Booth": { flatline: "040327" },
};

const juliusDeane = {
  Cyberdeck: { AI: 36112, "Fuji Electric": 3601 },
  Comlink: "",
  Icebreaker: "",
  "ROM construct": "",
  Cowboy: "",
  "Emperor Norton": "",
  Cyberjack: "",
  Ratz: { "Zion Cluster": 34770, "Chiba City": 3601 },
  Holografix: { "Asano Computing": 162324, "Hitachi Biotech": 473 },
  "Larry Moe": { Cryptology: 36112 },
  PAX: { "Space colony": "004713", "Holy Joystick": 254 },
  "Skill chips": { "Bank of Berne": 7107 },
  "Shin's Pawn": { Spacedock: 162324, "Ono-Sendai": 473 },
  "Gentleman Loser": { "Marcus Garvey": 34770, "Bank of Zurich": 7107 },
  "Maas Biolabs": { "Compu-judge": 254 },
  "Justice Booth": { flatline: "004713" },
};

const donutWorld = {
  Cyberdeck: { AI: 50127, "Fuji Electric": 3347 },
  Comlink: "",
  Icebreaker: "",
  "ROM construct": "",
  Cowboy: "",
  "Emperor Norton": "",
  Cyberjack: "",
  Ratz: { "Zion Cluster": 43267, "Chiba City": 3347 },
  Holografix: { "Asano Computing": "073611", "Hitachi Biotech": 614 },
  "Larry Moe": { Cryptology: 50127 },
  PAX: { "Space colony": "051435", "Holy Joystick": "017" },
  "Skill chips": { "Bank of Berne": 4102 },
  "Shin's Pawn": { Spacedock: "073611", "Ono-Sendai": 614 },
  "Gentleman Loser": { "Marcus Garvey": 43267, "Bank of Zurich": 4102 },
  "Maas Biolabs": { "Compu-judge": "017" },
  "Justice Booth": { flatline: "051435" },
};

const lawbot = {
  Cyberdeck: { AI: 74655, "Fuji Electric": 1777 },
  Comlink: "",
  Icebreaker: "",
  "ROM construct": "",
  Cowboy: "",
  "Emperor Norton": "",
  Cyberjack: "",
  Ratz: { "Zion Cluster": 21400, "Chiba City": 1777 },
  Holografix: { "Asano Computing": "061254", "Hitachi Biotech": 672 },
  "Larry Moe": { Cryptology: 74655 },
  PAX: { "Space colony": 157223, "Holy Joystick": 533 },
  "Skill chips": { "Bank of Berne": "0170" },
  "Shin's Pawn": { Spacedock: "061254", "Ono-Sendai": 672 },
  "Gentleman Loser": { "Marcus Garvey": 21400, "Bank of Zurich": "0170" },
  "Maas Biolabs": { "Compu-judge": 533 },
  "Justice Booth": { flatline: 157223 },
};

const database = {
  Cyberdeck: { AI: 67237, "Fuji Electric": 2730 },
  Comlink: "",
  Icebreaker: "",
  "ROM construct": "",
  Cowboy: "",
  "Emperor Norton": "",
  Cyberjack: "",
  Ratz: { "Zion Cluster": 65110, "Chiba City": 2730 },
  Holografix: { "Asano Computing": 127170, "Hitachi Biotech": 321 },
  "Larry Moe": { Cryptology: 67237 },
  PAX: { "Space colony": "056201", "Holy Joystick": 673 },
  "Skill chips": { "Bank of Berne": 5116 },
  "Shin's Pawn": { Spacedock: 127170, "Ono-Sendai": 321 },
  "Gentleman Loser": { "Marcus Garvey": 65110, "Bank of Zurich": 5116 },
  "Maas Biolabs": { "Compu-judge": 673 },
  "Justice Booth": { flatline: "056201" },
};

const shiva = {
  Cyberdeck: { AI: 34755, "Fuji Electric": 4327 },
  Comlink: "",
  Icebreaker: "",
  "ROM construct": "",
  Cowboy: "",
  "Emperor Norton": "",
  Cyberjack: "",
  Ratz: { "Zion Cluster": 61723, "Chiba City": 4327 },
  Holografix: { "Asano Computing": "067144", "Hitachi Biotech": "072" },
  "Larry Moe": { Cryptology: 34755 },
  PAX: { "Space colony": "054127", "Holy Joystick": 333 },
  "Skill chips": { "Bank of Berne": 6160 },
  "Shin's Pawn": { Spacedock: "067144", "Ono-Sendai": "072" },
  "Gentleman Loser": { "Marcus Garvey": 61723, "Bank of Zurich": 6160 },
  "Maas Biolabs": { "Compu-judge": 333 },
  "Justice Booth": { flatline: "054127" },
};

const freeside = {
  Cyberdeck: { AI: 23671, "Fuji Electric": "0703" },
  Comlink: "",
  Icebreaker: "",
  "ROM construct": "",
  Cowboy: "",
  "Emperor Norton": "",
  Cyberjack: "",
  Ratz: { "Zion Cluster": 51666, "Chiba City": "0703" },
  Holografix: { "Asano Computing": "031776", "Hitachi Biotech": 507 },
  "Larry Moe": { Cryptology: 23671 },
  PAX: { "Space colony": 114352, "Holy Joystick": 434 },
  "Skill chips": { "Bank of Berne": 5165 },
  "Shin's Pawn": { Spacedock: "031776", "Ono-Sendai": 507 },
  "Gentleman Loser": { "Marcus Garvey": 51666, "Bank of Zurich": 5165 },
  "Maas Biolabs": { "Compu-judge": 434 },
  "Justice Booth": { flatline: 114352 },
};

const softwarez = {
  Cyberdeck: { AI: 71724, "Fuji Electric": 6040 },
  Comlink: "",
  Icebreaker: "",
  "ROM construct": "",
  Cowboy: "",
  "Emperor Norton": "",
  Cyberjack: "",
  Ratz: { "Zion Cluster": 31270, "Chiba City": 6040 },
  Holografix: { "Asano Computing": "031770", "Hitachi Biotech": 725 },
  "Larry Moe": { Cryptology: 71724 },
  PAX: { "Space colony": 126443, "Holy Joystick": 300 },
  "Skill chips": { "Bank of Berne": "0017" },
  "Shin's Pawn": { Spacedock: "031770", "Ono-Sendai": 725 },
  "Gentleman Loser": { "Marcus Garvey": 31270, "Bank of Zurich": "0017" },
  "Maas Biolabs": { "Compu-judge": 300 },
  "Justice Booth": { flatline: 126443 },
};

const matrix = {
  Cyberdeck: { AI: "00206", "Fuji Electric": 5150 },
  Comlink: "",
  Icebreaker: "",
  "ROM construct": "",
  Cowboy: "",
  "Emperor Norton": "",
  Cyberjack: "",
  Ratz: { "Zion Cluster": 45771, "Chiba City": 5150 },
  Holografix: { "Asano Computing": 121777, "Hitachi Biotech": 571 },
  "Larry Moe": { Cryptology: "00206" },
  PAX: { "Space colony": "030654", "Holy Joystick": 410 },
  "Skill chips": { "Bank of Berne": 1053 },
  "Shin's Pawn": { Spacedock: 121777, "Ono-Sendai": 571 },
  "Gentleman Loser": { "Marcus Garvey": 45771, "Bank of Zurich": 1053 },
  "Maas Biolabs": { "Compu-judge": 410 },
  "Justice Booth": { flatline: "030654" },
};

const mattShaw = {
  Cyberdeck: { AI: 22372, "Fuji Electric": 6162 },
  Comlink: "",
  Icebreaker: "",
  "ROM construct": "",
  Cowboy: "",
  "Emperor Norton": "",
  Cyberjack: "",
  Ratz: { "Zion Cluster": 41317, "Chiba City": 6162 },
  Holografix: { "Asano Computing": 117327, "Hitachi Biotech": 430 },
  "Larry Moe": { Cryptology: 22372 },
  PAX: { "Space colony": "014527", "Holy Joystick": "054" },
  "Skill chips": { "Bank of Berne": 5423 },
  "Shin's Pawn": { Spacedock: 117372, "Ono-Sendai": 430 },
  "Gentleman Loser": { "Marcus Garvey": 41317, "Bank of Zurich": 5423 },
  "Maas Biolabs": { "Compu-judge": "054" },
  "Justice Booth": { flatline: "014527" },
};

const nightCityNews = {
  Cyberdeck: { AI: 42074, "Fuji Electric": 2174 },
  Comlink: "",
  Icebreaker: "",
  "ROM construct": "",
  Cowboy: "",
  "Emperor Norton": "",
  Cyberjack: "",
  Ratz: { "Zion Cluster": 61456, "Chiba City": 2174 },
  Holografix: { "Asano Computing": "011772", "Hitachi Biotech": 775 },
  "Larry Moe": { Cryptology: 42074 },
  PAX: { "Space colony": 132077, "Holy Joystick": 313 },
  "Skill chips": { "Bank of Berne": 3173 },
  "Shin's Pawn": { Spacedock: "011772", "Ono-Sendai": 775 },
  "Gentleman Loser": { "Marcus Garvey": 61456, "Bank of Zurich": 3173 },
  "Maas Biolabs": { "Compu-judge": 313 },
  "Justice Booth": { flatline: 132077 },
};

export const wheelData = {
  Chatsubo: chatsubo,
  Cyberspace: cyberspace,
  Gemeinschaft: gemeinschaft,
  "Crazy Edo": crazyEdo,
  Microsofts: microsofts,
  "Cheap Hotel": cheapHotel,
  "Julius Deane": juliusDeane,
  "Donut World": donutWorld,
  Lawbot: lawbot,
  database: database,
  Shiva: shiva,
  Freeside: freeside,
  softwarez: softwarez,
  Matrix: matrix,
  "Matt Shaw": mattShaw,
  "Night City News": nightCityNews,
};

export const outerRef = {
  Chatsubo: "chatsubo",
  Cyberspace: "cyberspace",
  Gemeinschaft: "gemeinschaft",
  "Crazy Edo": "crazyEdo",
  Microsofts: "microsofts",
  "Cheap Hotel": "cheapHotel",
  "Julius Deane": "juliusDeane",
  "Donut World": "donutWorld",
  Lawbot: "lawbot",
  database: "database",
  Shiva: "shiva",
  Freeside: "freeside",
  softwarez: "softwarez",
  Matrix: "matrix",
  "Matt Shaw": "mattShaw",
  "Night City News": "nightCityNews",
};

export const outerWheel = [
  "Chatsubo",
  "Cyberspace",
  "Gemeinschaft",
  "Crazy Edo",
  "Microsofts",
  "Cheap Hotel",
  "Julius Deane",
  "Donut World",
  "Lawbot",
  "database",
  "Shiva",
  "Freeside",
  "softwarez",
  "Matrix",
  "Matt Shaw",
  "Night City News",
];

export default wheelData;
